### ISSUE TITLE
Deleting app & reinstalling doesn't require FxA authentication upon opening

### ISSUE THREAD

**Issue by nickbrandt** [mozilla-lockbox/lockbox-ios#155]
Instead of requiring the user to authenticate again when reinstalling the app, it opens the app already on the Entry List screen.

**Comment by sashei** [comment]
Implementation notes:

This happens because the Keychain items associated with a given application are _not_ cleared when the app is uninstalled. We are unable to run our own code on uninstall, but can take advantage of other stored properties (e.g., UserDefaults) that do get cleared on uninstall, to clear any Keychain items associated with Lockbox on first run.
