### ISSUE TITLE
Update metrics.md telemetry based on latest requirements

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#180]
Once @sandysage has confirmed the requirements are ready, go review and update metrics.md.

- [X] Are you using Google Analytics or Ping Centre? - Telemetry
- [X] Metrics.md in the repo in a docs folder explaining the data being sent by the experiment
- [x] Metrics.md is updated to reflect the mvp requirements once designs are complete
- [ ] Review of metrics.md by a data analyst
- [ ] Data Collection Review from Peer/Adjacent https://wiki.mozilla.org/Firefox/Data_Collection
- ~Define what to do when the DNT flag is set~ (does not apply to mobile)
  - Add ability to disable Telemetry usage reporting at #258

Related to #258
Related to #58
Related to #296

**Comment by sandysage** [comment]
## Checklist to confirm this issue is 'done' when we review and update the metrics.md

- [X] Are you using Google Analytics or Ping Centre? - Telemetry
- [X] Metrics.md in the repo in a docs folder explaining the data being sent by the experiment
- [ ] Review of metrics.md by a data analyst
- [ ] Dashboard complete showing key metrics
- [ ] Data Collection Review from Rebecca (our data collection steward) https://wiki.mozilla.org/Firefox/Data_Collection
- [ ] Define what to do when the DNT flag is set

**Comment by sandysage** [comment]
P1 designs are here: https://mozilla.invisionapp.com/share/7JEUG47ZU#/screens/267561046

Things in this flow that are _not_ P1 candidates for launch include:
* onboarding: enable in browser
* entry detail: onboarding instructions for copy/paste
* entry detail: edit
* entry detail: delete
* entry detail: notes

With the mvp requirements defined (and outlined in the feature doc) and the designs drafted, I think we can now update the metrics.md with events to capture, and the analyses to track (specified in the [feature doc](https://docs.google.com/document/d/1q2xYGsoB0ylfir-Bkg8BwP4Aj1H6OjjJHW2FmX-JexU/edit?ts=5acba4a8#).

**Comment by sandysage** [comment]
This is moving forward for our app telemetry. Open items (added to the top) that will need to be included in our metrics.md are:
* Test Pilot experiment tracking
* SMS to app store link
