### ISSUE TITLE
Engineering acceptance criteria

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#204]
- [x] Scalability Plan. How many users are we expecting? (N/A, distributed through App Store and connects to existing Sync infra)
- [x] Hosting Plan. Is there a server side component? (N/A, distributed through App Store and connects to existing Sync infra)
- [x] Monitoring and Versioning end points set up (N/A)
- ~e10s compatible~
- ~Add-on is on testpilot.firefox.com/files/~
- [x] Localization Plan (post launch) #207 
- ~Add-on has the appropriate updateURL (N/A not an extension)~

**Comment by devinreams** [comment]
Discussed with Test Pilot team recently. Updated with considerations and responses above.

In short: these are N/A due to nature of this experiment being run through app store and connecting to existing Sync service and infrastructure. We're exploring handling error states (connecting to those services) gracefully #285 and will work on localization post-launch #207
