### ISSUE TITLE
Comment out the autolock setting, if not hooked up to lock

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#213]
If we do not have the conditions under which the app becomes locked with these settings, then we'll need to remove the autolock options from the settings list (one line to comment it out).

**Comment by devinreams** [comment]
Does "the conditions under which the app becomes locked" refer to the P2 work planned at #214? 

I just want to make sure we clearly connect dependencies/related items in descriptions. I'd rather over than under communicate as we come back to stuff in days/weeks because I definitely know I'll forget. 😄

**Comment by sandysage** [comment]
@devinreams Good point! Yes this refers to issue #214. If we're able to address the "locking" functionality as outlined in #214 prior to launch, then this issue becomes irrelevant.

**Comment by devinreams** [comment]
This is no longer applicable since #214 #236 is in place and complete
