### ISSUE TITLE
Timer for Copy Action

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#232]
Establish a standard, yet to be determined timer for copy actions within the app, so passwords don't stay on the clipboard for perpetuity...

**Comment by sandysage** [comment]
@linuxwolf @devinreams From our conversation this morning, it sounds like we need to consider dumping 'copied' items from the clipboard in some reasonable period of time. Is there a recommendation here?

_noting as blocked as it needs engineering review and considerations_

**Comment by devinreams** [comment]
@sashei @jhugman @linuxwolf after doing some quick reading on what other apps do, and given `UIPasteboardOption` can simply set an expiration date/time, I think our best option is to pick a reasonable expiration default and stick to that for now.  I don't believe backgrounding/killing the app is a concern since iOS 10 but may have read wrong. Please correct me or chime in if you disagree...

@mozilla-lockbox/product Either way, this is pretty straight forward to do. Would you like to pick a time and have us set something like "1 minute"? 1Password by comparison is set to 45 seconds.

---

Resources:

- https://developer.apple.com/documentation/uikit/uipasteboardoption
