### ISSUE TITLE
Loading Indication for Initial Sync Import

### ISSUE THREAD

**Issue by changecourse** [mozilla-lockbox/lockbox-ios#233]
When loading up my entries for the very first time, I should be given an affordance of something happening within the app, e.g., a loading indication, if it takes more than two seconds to load and import the data into the app.

## Visual Design
**InVision**
https://mozilla.invisionapp.com/share/BQEUSO0S2#/290701009_Entry_List_-_Syncing

**Zeplin**
https://zpl.io/2Ejdl78

**Comment by changecourse** [comment]
@sandysage we've begun working on designs to address this; will update the description once complete

**Comment by changecourse** [comment]
mobile-eng ready for review and placement into the backlog.

**Comment by devinreams** [comment]
@mozilla-lockbox/mobile-engineering any immediate concerns with this "loading" indicator and "empty/placeholder" imagery for the list view? I didn't spot anything egregious, the experience seemed pretty standard but I defer to your expertise:

Any questions or "gotchas" to bring up with the UX team and re-consider before we move this to the backlog?

**Comment by devinreams** [comment]
Discussed briefly with the team today and got a quick :+1: to proceed as designed. Adding to backlog at the bottom-ish.

**Comment by sashei** [comment]
@changecourse @nickbrandt Taking a closer look as I start to think about implementation, and I have a few questions / points of clarification:

- In the issue description, you say that we should show this loading screen if the sync is going to take >2 seconds. There's no way to know how long it will take to sync, so I'm going to default to showing it every time & we can finetune if things are feeling too blinky with the view animations.
- The A-Z selector looks disabled in the mockup but the settings button does not; is that intentional?
- should users be able to select the search bar while syncing? (would prefer not)

**Comment by changecourse** [comment]
Can I confirm that the work being done here also removes the chest and all previous copy @sashei ? Thanks!

**Comment by sashei** [comment]
@changecourse I am not removing the chest right now; it will be displayed in the scenario that the user has synced but has no entries available. I can certainly remove it as part of this story though.

**Comment by changecourse** [comment]
@sashei yes it would be nice to remove all imagery and copy from the previously designed 'empty state' as part of this effort... just to clean up the artifacts referencing the extension. 

The entry list placeholder image will be included (that shows placeholder rows of an entry table) as part of this issue though, correct?
