### ISSUE TITLE
Fix changing preferred browser

### ISSUE THREAD

**Issue by joeyg** [mozilla-lockbox/lockbox-ios#264]
Right now ExternalLinkActionHandler subscribes to preferred browser setting changes resulting in the browser opening unexpectedly.

Steps to reproduce
1. Open app and tap on a lockbox list item
2. Go back to the app
3. Go to Settings->Preferred Browser
4. Change browser

Expected Result: The setting changes
Actual Result: The new browser opens with the previously clicked on items

**Comment by sashei** [comment]
Rather than subscribing to a `Store` type in an `ActionHandler`, the method signature on the `ActionHandler` should be changed from `invoke(_ action: ExternalLinkAction)` to `openURL(action: ExternalLinkAction, browser: PreferredBrowserSetting)`.

**Comment by joeyg** [comment]
Couldn’t the ActionHandler just pull the preferred browser from UserDefaults directly instead of subscribing? It seems inconvenient to have to lookup the browser setting in each presenter that wants to open a link

**Comment by sashei** [comment]
Hm, I agree with you on the inconvenience factor... the other solution is to use `take(1)` so that the subscription goes away after a single emission. I trend towards strict adherence to separation of concerns between storage accessing (only in presenters) and outside-of-application calls (only in actionhandlers), but I think this is an implementer's choice kind of problem :p
