### ISSUE TITLE
Autolock timer still locks while interacting with app

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#463]
I think the same or similar to #405 presumably fixed at #418 is still happening in some cases. The autolock fired while using the app at #455 and I experienced it myself recently but just once, and not sure on what branch.

I can’t tell what state gets us back here, as the timer is _typically_ working fine (set to 1 minute timer, tap around during the 60 seconds, does not lock) but... perhaps when resuming the app from the background or unlocking or something, it seems we can still get interrupted when interacting with the app, it will just lock on me and drop me out to the Welcome screen.

I’m opening this for tracking to see a) if others experience this issue again and can weigh in here and b) can provide consistently reproducible steps or behavior that causes this.

Marking as a P2 as I don’t think this is actionable without more information...

**Comment by isabelrios** [comment]
I have found steps to reproduce the autolock (or is a different issue?), just in case it helps:
-Set autolock to 1 minute o tap on Lock Now
-When the Locked screen is shown, tap on cancel
-Close the app and launch it again
-Enter the correct passcode
-The app is unlocked successfully but just after a few seconds the lock screen is shown again.

Please see here: https://youtu.be/opFDG4FO9IE

**Comment by sandysage** [comment]
@isabelrios I wasn't able to reproduce this finding using the steps provided.

But I did see this happen twice during a user research session. This is concerning because it creates confusion when a user (or research participant) doesn't know why the app is asking for a fingerprint in the middle of an action.

Steps taken:
- download the app via TestFlight
- first run the app - welcome screen, fxa sign in, email confirmation, entry list
- while in the entry list on first run, the screen locked and prompted for TouchID
   - this happened in less than a minute of running in the app
- later in the session, viewing entry details, screen locked and prompted for TouchID
   - this happened in less than the 5 minutes, and the autolock timer wasn't changed from the default yet

@devinreams @sashei what, if anything, can we do here? I realize this is intermittent and hard to replicate (impossible?), but it's keeps coming up.

**Comment by sandysage** [comment]
Let me know if this is a different finding, as this intermittent locking doesn't seem to be related to the autolock timer setting.

**Comment by devinreams** [comment]
See also #504 as some discussion this morning suggested the datastore may be the cause...

**Comment by sashei** [comment]
Note: not fixed by #514

**Comment by sandysage** [comment]
From pull request #514:
> I think there's a more elegant solution here around combining the locked setting / Autolock timer but there's a larger refactor required and both of these issues seem fairly pressing UX / security wise. Also it seems like some of the expected DataStore APIs may be subject to change anyway.

When does it make sense to circle back to this issue? What changes are expected with the DataStore APIs in the near future versus down the road?

While noted as a P1 because this is still happening, we want to be smart with our efforts. There is no need to try to fix this now if we expect this to be a non-issue here soon.

**Comment by devinreams** [comment]
With the refactor at #586 and my continued testing (Build 1846 was latest today) I believe we can confidently close this as the locking timer is now improved for both the storage locking and user experience.

Please feel free to re-open if anyone finds this happening again...
