### ISSUE TITLE
most buttons and text labels do not respect and adjust to "larger text" / dynamic sizes

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#470]
From #441 

### Text Style Definitions
https://mozilla.invisionapp.com/share/3ALGEQ8RDM9#/304386170_Text-Styles

Combined Logo & Tagline Image:
[logo.zip](https://github.com/mozilla-lockbox/lockbox-ios/files/2121236/logo.zip)

**Comment by sashei** [comment]
@nickbrandt @changecourse 

I'm working through this (semi-tedious :p) bug right now, and with Apple's dynamic text `textStyle`s there is not a way to specify things like font sizes -- each label will need to have one of the font scales as listed in this [Apple documentation](https://developer.apple.com/documentation/uikit/uifont/textstyle). I've been just eyeballing these as I go so far, but I was wondering if y'all wanted to do a more involved audit with those size guidelines in mind or just come in behind me and check what I've put together when I'm done.

**Comment by sashei** [comment]
I thought it would be useful to attach some images of what I'm describing. Particularly, things like "Take your passwords everywhere" lose some of their styling (italics, custom font). At what point do we want to triage  (is everything important for vision-impaired people to read?) for the sake of preserving the design, vs. shifting the design for accessibility? Also, do we want to factor in any design changes to better accommodate the larger text? 

I found this useful github gist with the sizes for the default font for the user-selected size preference: https://gist.github.com/sprynmr/7903469

I bring this up only because for the most part, we use the system font throughout the application and the workaround for preserving custom fonts / styles is less trivial than what I've been doing so far. However, I'm happy to get the infrastructure for it in place if we decide that those properties are design essentials.

![Dynamic text with large size](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5948791808f380001b59534b/125516c66e82c728ace21e0d46db9d97368e82bd80fbff70a74ff5912706147b2610e366308cd320b04c7e41584f53bc43585e4ce1f98f36a4b62c21ce4c0be5cf6d5c6ac33d03b0aac25de05bef73cf5d8fa4b98318c4bc3526e48fdc1b6819071889fd5830f4ca1d990ee457f30f04fa47693ebf3c633e559e0c742b616623a9f5da56848265a6b3142d4485.png)
![Dynamic text with small / normal size](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5948791808f380001b59534b/125516c66e82c728ace21e0d46db9d97368e82bd80fbff70a74ff5912706147b2610e366308cd320b04c7e41584f53bc43585e4ce1f98f36a4b62c21ce4c0be5cf6d596ac23b03b0aac25de05bef73cf5d8fa4b98318c4bc3526e48fdc1b6819071889fd5830f4ca1d990ee457f30f04fa47693ebf3c633e559e0c7425616623a9f5da56848265a6b314274485.png)
![what's on master right now](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/5948791808f380001b59534b/125516c66e82c728ace21e0d46db9d97368e82bd80fbff70a74ff5912706147b2610e366308cd320b04c7e41584f53bc43585e4ce1f98f36a4b62c21ce4c0be5cf6d586ac53c03b0aac25de05bef73cf5d8fa4b98318c4bc3526e48fdc1b6819071889fd5830f4ca1d990ee457f30f04fa47693ebf3c633e559e0c742b616623a9f5da56848265a6b315294485.png)

**Comment by devinreams** [comment]
The big questions:

- Do we want to continue to support custom fonts?
- Do we want those custom fonts to be dynamic sizeable? (if so, we have to define the [categories](https://gist.github.com/sprynmr/7903469) for all possible sizes on dynamic size slider)
- Therefore: should we remove all explicit sizes and set the size [categories](https://gist.github.com/sprynmr/7903469) in designs?

Perhaps @mozilla-lockbox/product can review today and we can discuss as a team tomorrow morning?

**Comment by nickbrandt** [comment]
@sashei @devinreams @changecourse 
We put together an annotation document that maps our current styles to Apple text styles (link in description above). Most everything mapped pretty nicely, though there were some elements where the desired font weight wasn't available as an Apple style. In order to have our own custom weights with dynamic sizing, it would require a good amount of dev effort. If we do find out the changes in weight to be problematic, we can open a new issue and prioritize that work.

In addition, the only areas where we are using fonts outside of SFUI are the logo and tagline. To preserve the tagline styling, we are proposing to just combine that with the wordmark into 1 image (also attached above).
