### ISSUE TITLE
Visual issues of rating option from Feedback page 

### ISSUE THREAD

**Issue by SorinaFlorean** [mozilla-lockbox/lockbox-ios#523]
Environment:
Device: iPhone SE (11.0.1)
Lockbox version 1.1 (1552)

Steps to reproduce:

Open Lockbox app;
Go to settings -> Send Feedback.
Actual results:

"x" too close to the star
"x" too small compared to the stars
the stars are not centered
Expected results: no visual issues are displayed.

![img_0012](https://user-images.githubusercontent.com/24588037/42095417-3de083f6-7bbb-11e8-83f2-ab977859a718.PNG)

**Comment by sandysage** [comment]
We're limited to SurveyGizmo styles, so there isn't a lot we can do here. That said @nickbrandt added some padding between the 'reset' X and the stars. Hopefully that cleans it up the visual issues enough so that a user better understands the use of that X.

Closing as complete.

![IMG_4593DB8420EE-1.jpeg](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/59dc07ab1a9a2600115c9b6f/125516c66e82c728ace21e0d46c1b9bd1cd6d6f0dccd9d1bf00fa0b10c0b76316546b3397f8fe62bab0021435a561aa815505c47f8aadd7da1b43c7088590eb9823b0e22d42103eee9dc4be05ce36ade0d97bcae8b4bcae93826e48a8b4b391b0c1a88fc4f78.jpeg)
