### ISSUE TITLE
Populate `ASCredentialIdentityStore` when enabling Lockbox as an autofill credential provider

### ISSUE THREAD

**Issue by sashei** [mozilla-lockbox/lockbox-ios#612]
### Acceptance Criteria

- Construct `ASPasswordCredentialIdentity` items and pass them to the `ASCredentialIdentityStore.shared` in the background
- Display a nice loading indicator / confirmation on completion
 - Items from Lockbox are displayed in the QuickType bar

### Visual Design

**InVision**
Authenticate with biometrics or passcode (if neither is set up, bypass this step)
https://mozilla.invisionapp.com/share/RWEHBJQH9#/313158428_AutoFill_-_Autofill_Passwords_-_Enable

Display loading indicator
https://mozilla.invisionapp.com/share/RWEHBJQH9#/313158426_AutoFill_-_Autofill_Passwords_-_Enable_-_Loading

**Zeplin**
Step 1: https://zpl.io/VQYeXdP
Step 2: https://zpl.io/agvK4OR

**Comment by nickbrandt** [comment]
@sashei this brings up a good question. @changecourse  and I were actually discussing yesterday if it even made sense to authenticate for enabling Lockbox as a provider, since they would still need to authenticate in order to use the logins. Are there any implications to not requiring the user to authenticate to enable? I'm not able to find much documentation about this. From reviewing the deck that was provided, it seems they only discuss authentication as optional for the extension prior to displaying the credential list.

**Comment by sashei** [comment]
@nickbrandt @changecourse I can't think of any implications of not requiring the user to authenticate while enabling; I was thinking about it as more security theater tbh. Maybe @linuxwolf has some thoughts here?

**Comment by linuxwolf** [comment]
I think I lean toward _not_ requiring an auth confirmation.

Requiring the prompt might help people feel more trust in turning it on, but I think there are more downsides (more failure paths) for something that doesn't really buy the user any extra security.  Credentials aren't exposed just because this is enabled/disabled.

As long as the user has to unlock (based on app conditions) before the credentials are filled, I don't think this "auth to enable" does anything meaningful, and we can skip it.

**Comment by linuxwolf** [comment]
I think we can wait for user feedback on this; if there's enough concern, we can look at ways the user can tell us to populate or de-populate the ASCredentialStore (e.g., another setting!).  RIght now, though, I don't think there's that much risk to usernames and domains being exposed to the OS.
