### ISSUE TITLE
Desktop feature request: VCS integration.

### ISSUE THREAD

**Issue by mhoye** [mozilla-lockbox/lockbox-ios#623]
Low-priority feature request:  While I recognize that there are some thorny security and UI issues involved here, I think that it would be very good if developers could reliably have precommit hooks in their version control systems that let their VCS prevent them from checking passwords or auth tokens into public repositories.

**Comment by sandysage** [comment]
@mhoye Than you for the thoughtful consideration. I'm going to keep track of this request as part of our broader product initiative. Right now we don't have a project where we can best keep up with this within GitHub; keeping this with the iOS app wouldn't be  accurate. I'm going to go ahead and close this issue here. And follow up as when we can revisit this request.
