### ISSUE TITLE
Capture autofill telemetry events

### ISSUE THREAD

**Issue by sandysage** [mozilla-lockbox/lockbox-ios#624]
As the product owner, I want to know:

- is this feature discoverable and can people set it up (enabling it)?
- are people are using this feature (filling a credential)?
- how often do we have a matching result in the quicktype bar versus the user going to the Lockbox list view?
- where are they dropping off? can people complete the task of logging in?

Are just a few I can think of off the top of my head. @lrrationalagent, I opened this issue so that we:

- [ ] identify any additional questions we want to answer with this feature
- [ ] capture the additional events here and in our metrics.md
- [ ] add the events

**Comment by irrationalagent** [comment]
We'd like, at a minimum, to have events for the following actions:
- [ ] autofill enabled in app (if there is more than one way to do this e.g. thru onboarding or thru settings, its OK to have a generic event that covers all touchpoints. if its not extra work to have a unique event per touchpoint, then let's do that)
- [ ] telemetry event corresponding to `provideCredentialWithoutUserInteraction` (credential provided directly to quicktype
- [ ] telemetry event corresponding to `prepareCredentialList` (credential list displayed)
- [ ] some event corresponding to a successful autofill. lmk if this is hard - I think its relatively important to have since it allows us to know, in combination with two events prior, the proportion of people initiating the autofill process that actually get to the desired end-state. but i get that this may not be possible on our end (i.e. the actual filling is done outside of lockbox, and we don't get any sort of callback)

nice to have if easy to do:
- [ ] for `prepareCredentialList` related events, pass the number of entries in the filtered list to the `value` field of the event
- [ ] prompt to unlock displayed when trying to autofill
- [ ] unlock successful/unsuccessful when trying to autofill

if we had the lock/unlock events we could know for sure if people are getting tripped up at that step, if it happens that the number of successful autofills is much smaller than the number that are initiated. if we don't have those events, then we will just have to infer that it might be an issue with the locking without knowing 100%.
