### ISSUE TITLE
Hook up Learn More links in AutoFill entry list

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#723]
Spun out of #712. A leftover todo after #616 and #682:

**Comment by jhugman** [comment]
This is larger and more serious than it might otherwise seem. 

 1. In the event of no matching hosts or usernames, the extension crashies.
 2. It's unclear how we display this: the simplest would be to launch the preferred browser; alternatives would be launch `ExternalWebsiteNavigationController`. (unclear as in: no designs, and I don't know if Apple allows launching apps from extensions).
