### ISSUE TITLE
codecov has dropped to 0%

### ISSUE THREAD

**Issue by mcomella** [mozilla-lockbox/lockbox-ios#749]
https://codecov.io/gh/mozilla-lockbox/lockbox-ios

Not sure if it will fix itself or not!

**Comment by devinreams** [comment]
Thanks for opening this up. It fixes itself sometimes but has been "stuck" not reporting.

<img width="329" alt="screen shot 2018-09-20 at 12 43 14 pm" src="https://user-images.githubusercontent.com/49511/45839922-dce5c580-bcd2-11e8-85e5-3420a0357c05.png">


Not sure if related to the addition of the CredentialProvider extension. I was going to look into it but lost track. Thanks again...

**Comment by devinreams** [comment]
I still can't tell if there's anything we should be doing differently. I think Xcode is crashing on occasion and so not reporting the coverage accurately.

Generally once everything goes smoothly/successfully, the coverage reports properly (as it is now):

![screen shot 2018-09-25 at 2 56 15 pm](https://user-images.githubusercontent.com/49511/46042696-4c90f180-c0d3-11e8-997a-c4b1052ac580.png)
![screen shot 2018-09-25 at 2 56 20 pm](https://user-images.githubusercontent.com/49511/46042698-4d298800-c0d3-11e8-9cbd-04d51abfdfaa.png)

I'll close this as "fixed" (kinda) for now but if anyone has suggestions on how to improve/harden this please chime in because I'm fresh out of ideas. 😔
