### ISSUE TITLE
Can not upload to iTunes Connect since build 2812

### ISSUE THREAD

**Issue by devinreams** [mozilla-lockbox/lockbox-ios#855]
>Invalid Bundle. Your app supports Multitasking on iPad, so you must include the launch storyboard file, 'LaunchScreen~ipad.storyboard', in your bundle, 'org.mozilla.ios.Lockbox’. Learn more (https://developer.apple.com/documentation/uikit/uitraitcollection).

**Comment by toxikman** [comment]
This fix works, but it's not the best/correct fix. The problem is that you're adding a ".storyboard" extension after the Launch Screen name. If you remove that, you don't need the UIRequiresFullScreen~ipad hack, you can just report "UIRequiresFullScreen" false for all devices. The App Store upload validator will be able to find the storyboard if it's just the name part without the extension.
